title: Apiviz documentation
logo: /static/logos/logo_apiviz_icon_15.png
description: Documentation about Apiviz instanciation
show_downloads: true
# theme: jekyll-theme-minimal
remote_them : "mmistakes/minimal-mistakes@4.16.3"
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-include-cache