# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Apiviz
masthead_title: "Apiviz docs"
logo : /static/logos/logo_apiviz_icon_15.png
email: codemos.infos@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  official documentation for Apiviz instanciation, 
  make a full website from raw data with the Apiviz eco-sytem
twitter_username: jparis_py
github_username: JulienParis
repository: "co-demos/apiviz-frontend"

minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /posts/page:num/
timezone: FR # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _docs

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# author:
#   name   : "Julien Paris"
#   avatar : "/assets/images/bio-photo.jpg"
#   bio    : "My awesome biography constrained to a sentence or two goes here."
#   links:
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       url: "https://"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jparis_py"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/co-demos/apiviz-frontend"


defaults:

  # _docs
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      sidebar:
        nav: "docs"

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "docs"

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/