title: Apiviz documentation
logo: /static/logos/logo_apiviz_icon_15.png
description: Documentation about Apiviz instanciation
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap