version: '3'

services:
  nuxt:
    build: 
      context: ./
      dockerfile: Dockerfile.nuxt
    container_name: ${APP}-nuxt
    restart: always
    ports:
      - "3333:3000"
    command:
      "npm run dev"

  nginx:
    image: nginx:1.13
    container_name: ${APP}-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
