version: '3'

services:

  nuxt:
    build: 
      context: ${APP_PATH}
      dockerfile: Dockerfile.nuxt
    container_name: ${APP}-nuxt
    restart: always
    environment : 
      - HOST=0.0.0.0
    ports:
      - "3333:3000"
    command: 
      npm run dev
    volumes:
      - .:/app
      - /app/node_modules/
      
  nginx:
    image: nginx:1.13
    container_name: ${APP}-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
